/**
 * Lab test name normalizer — maps 165+ biomarker name variations to canonical names.
 * Based on Superpower Biomarker Reference Ranges (13 categories, 165 biomarkers).
 * Used to enable cross-report biomarker comparisons, scoring, and derived calculations.
 */

const CANONICAL_MAP = {
  // ═══════════════════════════════════════════════════════════════════════════
  // HEART & VASCULAR — 30 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  non_hdl_cholesterol: {
    displayName: 'Non-HDL Cholesterol',
    category: 'heart_vascular',
    aliases: ['non-hdl cholesterol', 'non hdl cholesterol', 'non-hdl-c', 'non hdl-c'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 38.67 },
    defaultRefMin: null,
    defaultRefMax: 160,
    optimalMin: null,
    optimalMax: 130,
    panelTag: 'Core Panel',
  },
  hdl: {
    displayName: 'HDL Cholesterol',
    category: 'heart_vascular',
    aliases: ['hdl cholesterol', 'hdl-c', 'hdl cholesterol direct', 'high density lipoprotein'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 38.67 },
    defaultRefMin: 40,
    defaultRefMax: 999,
    optimalMin: 60,
    optimalMax: null,
    panelTag: 'Core Panel',
  },
  triglycerides: {
    displayName: 'Triglycerides',
    category: 'heart_vascular',
    aliases: ['triglycerides', 'triglyceride', 'trigs', 'tg'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 88.57 },
    defaultRefMin: 0,
    defaultRefMax: 150,
    optimalMin: null,
    optimalMax: 100,
    panelTag: 'Core Panel',
  },
  ldl: {
    displayName: 'LDL Cholesterol',
    category: 'heart_vascular',
    aliases: ['ldl cholesterol', 'ldl-c', 'ldl cholesterol calc', 'ldl cholesterol calculated', 'ldl direct', 'low density lipoprotein'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 38.67 },
    defaultRefMin: 0,
    defaultRefMax: 130,
    optimalMin: null,
    optimalMax: 100,
    panelTag: 'Core Panel',
  },
  cholesterol_hdl_ratio: {
    displayName: 'Cholesterol / HDL Ratio',
    category: 'heart_vascular',
    aliases: ['cholesterol/hdl ratio', 'total cholesterol/hdl', 'castelli risk index i', 'chol/hdl ratio', 'tc/hdl ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 5.0,
    optimalMin: null,
    optimalMax: 3.5,
    panelTag: 'Derived',
    isDerived: true,
  },
  ldl_hdl_ratio: {
    displayName: 'LDL / HDL Ratio',
    category: 'heart_vascular',
    aliases: ['ldl/hdl ratio', 'castelli risk index ii', 'ldl to hdl ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 3.0,
    optimalMin: null,
    optimalMax: 2.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  cholesterol_total: {
    displayName: 'Total Cholesterol',
    category: 'heart_vascular',
    aliases: ['cholesterol', 'total cholesterol', 'cholesterol total', 'cholesterol, total', 'serum cholesterol'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 38.67 },
    defaultRefMin: null,
    defaultRefMax: 200,
    optimalMin: null,
    optimalMax: 180,
    panelTag: 'Core Panel',
  },
  apob: {
    displayName: 'Apolipoprotein B (ApoB)',
    category: 'heart_vascular',
    aliases: ['apolipoprotein b', 'apo b', 'apob', 'apolipoprotein b-100'],
    defaultUnit: 'mg/dL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 90,
    optimalMin: null,
    optimalMax: 80,
    panelTag: 'Core Panel',
  },
  lpa: {
    displayName: 'Lipoprotein (a)',
    category: 'heart_vascular',
    aliases: ['lipoprotein a', 'lp(a)', 'lp a', 'lipoprotein(a)'],
    defaultUnit: 'nmol/L',
    conversions: { 'mg/dL': v => v * 2.4 },
    defaultRefMin: null,
    defaultRefMax: 125,
    optimalMin: null,
    optimalMax: 75,
    panelTag: 'Advanced',
  },
  ldl_particle_number: {
    displayName: 'LDL-P (Particle Number)',
    category: 'heart_vascular',
    aliases: ['ldl-p', 'ldl particle number', 'ldl particles', 'ldl particle count'],
    defaultUnit: 'nmol/L',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 1300,
    optimalMin: null,
    optimalMax: 1000,
    panelTag: 'Advanced',
  },
  small_ldl_p: {
    displayName: 'Small LDL-P',
    category: 'heart_vascular',
    aliases: ['small ldl-p', 'small ldl particles', 'small dense ldl particles', 'small ldl particle number'],
    defaultUnit: 'nmol/L',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 600,
    optimalMin: null,
    optimalMax: 400,
    panelTag: 'Advanced',
  },
  ldl_size: {
    displayName: 'LDL Size',
    category: 'heart_vascular',
    aliases: ['ldl size', 'ldl particle size', 'mean ldl size'],
    defaultUnit: 'nm',
    conversions: {},
    defaultRefMin: 20.5,
    defaultRefMax: null,
    optimalMin: 21.3,
    optimalMax: null,
    panelTag: 'Advanced',
  },
  hdl_particle_number: {
    displayName: 'HDL-P (Particle Number)',
    category: 'heart_vascular',
    aliases: ['hdl-p', 'hdl particle number', 'hdl particles'],
    defaultUnit: 'µmol/L',
    conversions: {},
    defaultRefMin: 30.5,
    defaultRefMax: null,
    optimalMin: 34.9,
    optimalMax: null,
    panelTag: 'Advanced',
  },
  large_hdl_p: {
    displayName: 'Large HDL-P',
    category: 'heart_vascular',
    aliases: ['large hdl-p', 'large hdl particles'],
    defaultUnit: 'µmol/L',
    conversions: {},
    defaultRefMin: 5.5,
    defaultRefMax: null,
    optimalMin: 7.3,
    optimalMax: null,
    panelTag: 'Advanced',
  },
  hdl_size: {
    displayName: 'HDL Size',
    category: 'heart_vascular',
    aliases: ['hdl size', 'hdl particle size', 'mean hdl size'],
    defaultUnit: 'nm',
    conversions: {},
    defaultRefMin: 8.7,
    defaultRefMax: null,
    optimalMin: 9.4,
    optimalMax: null,
    panelTag: 'Advanced',
  },
  large_vldl_p: {
    displayName: 'Large VLDL-P',
    category: 'heart_vascular',
    aliases: ['large vldl-p', 'large vldl particles'],
    defaultUnit: 'nmol/L',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 2.2,
    optimalMin: null,
    optimalMax: 1.4,
    panelTag: 'Advanced',
  },
  vldl_size: {
    displayName: 'VLDL Size',
    category: 'heart_vascular',
    aliases: ['vldl size', 'vldl particle size'],
    defaultUnit: 'nm',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 43,
    optimalMin: null,
    optimalMax: 38,
    panelTag: 'Advanced',
  },
  aip: {
    displayName: 'Atherogenic Index of Plasma (AIP)',
    category: 'heart_vascular',
    aliases: ['aip', 'atherogenic index of plasma', 'atherogenic index'],
    defaultUnit: 'log(TG/HDL)',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.21,
    optimalMin: null,
    optimalMax: 0.11,
    panelTag: 'Derived',
    isDerived: true,
  },
  tg_hdl_ratio: {
    displayName: 'TG / HDL Ratio',
    category: 'heart_vascular',
    aliases: ['tg/hdl ratio', 'triglyceride hdl ratio', 'triglyceride to hdl ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 3.0,
    optimalMin: null,
    optimalMax: 1.8,
    panelTag: 'Derived',
    isDerived: true,
  },
  nhr: {
    displayName: 'Neutrophil-to-HDL Ratio (NHR)',
    category: 'heart_vascular',
    aliases: ['nhr', 'neutrophil to hdl ratio', 'neutrophil-to-hdl ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 4.0,
    optimalMin: null,
    optimalMax: 3.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  atherogenic_coefficient: {
    displayName: 'Atherogenic Coefficient',
    category: 'heart_vascular',
    aliases: ['atherogenic coefficient', 'ac'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 4.0,
    optimalMin: null,
    optimalMax: 3.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  ldl_total_chol_ratio: {
    displayName: 'LDL-C / Total Cholesterol Ratio',
    category: 'heart_vascular',
    aliases: ['ldl/total cholesterol ratio', 'ldl-c/tc ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.6,
    optimalMin: null,
    optimalMax: 0.5,
    panelTag: 'Derived',
    isDerived: true,
  },
  ldl_apob_ratio: {
    displayName: 'LDL-C / ApoB Ratio',
    category: 'heart_vascular',
    aliases: ['ldl/apob ratio', 'ldl-c/apob ratio'],
    defaultUnit: 'mg/mg',
    conversions: {},
    defaultRefMin: 1.0,
    defaultRefMax: null,
    optimalMin: 1.2,
    optimalMax: null,
    panelTag: 'Derived',
    isDerived: true,
  },
  non_hdl_apob_ratio: {
    displayName: 'Non-HDL-C / ApoB Ratio',
    category: 'heart_vascular',
    aliases: ['non-hdl/apob ratio', 'non-hdl-c/apob ratio'],
    defaultUnit: 'mg/mg',
    conversions: {},
    defaultRefMin: 1.2,
    defaultRefMax: null,
    optimalMin: 1.4,
    optimalMax: null,
    panelTag: 'Derived',
    isDerived: true,
  },
  non_hdl_total_chol_ratio: {
    displayName: 'Non-HDL-C / Total Cholesterol Ratio',
    category: 'heart_vascular',
    aliases: ['non-hdl/tc ratio', 'non-hdl-c/total cholesterol ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.75,
    optimalMin: null,
    optimalMax: 0.7,
    panelTag: 'Derived',
    isDerived: true,
  },
  uric_acid_hdl_ratio: {
    displayName: 'Uric Acid / HDL-C Ratio',
    category: 'heart_vascular',
    aliases: ['uric acid/hdl ratio', 'ua/hdl ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 6.0,
    optimalMin: null,
    optimalMax: 4.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  vldl: {
    displayName: 'VLDL Cholesterol',
    category: 'heart_vascular',
    aliases: ['vldl', 'vldl cholesterol', 'vldl-c', 'very low density lipoprotein'],
    defaultUnit: 'mg/dL',
    conversions: {},
    defaultRefMin: 5,
    defaultRefMax: 40,
    optimalMin: null,
    optimalMax: 30,
    panelTag: 'Core Panel',
  },
  adma: {
    displayName: 'ADMA',
    category: 'heart_vascular',
    aliases: ['adma', 'asymmetric dimethylarginine'],
    defaultUnit: 'µmol/L',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.75,
    optimalMin: null,
    optimalMax: 0.60,
    panelTag: 'Advanced',
  },
  sdma: {
    displayName: 'SDMA',
    category: 'heart_vascular',
    aliases: ['sdma', 'symmetric dimethylarginine'],
    defaultUnit: 'µmol/L',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.60,
    optimalMin: null,
    optimalMax: 0.50,
    panelTag: 'Advanced',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LIVER HEALTH — 14 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  alt: {
    displayName: 'ALT (SGPT)',
    category: 'liver',
    aliases: ['alt', 'sgpt', 'alanine aminotransferase', 'alanine transaminase', 'alt/sgpt', 'sgpt/alt'],
    defaultUnit: 'U/L',
    conversions: {},
    defaultRefMin: 7,
    defaultRefMax: 56,
    optimalMin: null,
    optimalMax: 35,
    panelTag: 'Core Panel',
  },
  ast: {
    displayName: 'AST (SGOT)',
    category: 'liver',
    aliases: ['ast', 'sgot', 'aspartate aminotransferase', 'aspartate transaminase', 'ast/sgot', 'sgot/ast'],
    defaultUnit: 'U/L',
    conversions: {},
    defaultRefMin: 10,
    defaultRefMax: 40,
    optimalMin: null,
    optimalMax: 25,
    panelTag: 'Core Panel',
  },
  alp: {
    displayName: 'Alkaline Phosphatase',
    category: 'liver',
    aliases: ['alkaline phosphatase', 'alp', 'alk phos', 'alkp'],
    defaultUnit: 'U/L',
    conversions: {},
    defaultRefMin: 44,
    defaultRefMax: 147,
    optimalMin: null,
    optimalMax: 80,
    panelTag: 'Core Panel',
  },
  ggt: {
    displayName: 'GGT',
    category: 'liver',
    aliases: ['ggt', 'gamma glutamyl transferase', 'gamma gt', 'gamma-glutamyl transpeptidase', 'ggtp', 'gamma glutamyltransferase (ggt)', 'gamma glutamyltransferase'],
    defaultUnit: 'U/L',
    conversions: {},
    defaultRefMin: 0,
    defaultRefMax: 61,
    optimalMin: null,
    optimalMax: 30,
    panelTag: 'Core Panel',
  },
  albumin: {
    displayName: 'Albumin',
    category: 'liver',
    aliases: ['albumin', 'serum albumin', 'albumin, serum'],
    defaultUnit: 'g/dL',
    conversions: { 'g/L': v => v / 10 },
    defaultRefMin: 3.5,
    defaultRefMax: 5.0,
    optimalMin: 4.0,
    optimalMax: 5.0,
    panelTag: 'Core Panel',
  },
  total_protein: {
    displayName: 'Total Protein',
    category: 'liver',
    aliases: ['total protein', 'protein total', 'protein, total', 'serum protein'],
    defaultUnit: 'g/dL',
    conversions: { 'g/L': v => v / 10 },
    defaultRefMin: 6.3,
    defaultRefMax: 8.2,
    optimalMin: 7.0,
    optimalMax: 7.9,
    panelTag: 'Core Panel',
  },
  globulin: {
    displayName: 'Globulin',
    category: 'liver',
    aliases: ['globulin', 'serum globulin'],
    defaultUnit: 'g/dL',
    conversions: {},
    defaultRefMin: 2.0,
    defaultRefMax: 3.5,
    optimalMin: 2.4,
    optimalMax: 3.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  ag_ratio: {
    displayName: 'Albumin / Globulin Ratio',
    category: 'liver',
    aliases: ['a/g ratio', 'albumin/globulin ratio', 'ag ratio', 'albumin globulin ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: 1.1,
    defaultRefMax: 2.5,
    optimalMin: 1.7,
    optimalMax: null,
    panelTag: 'Derived',
    isDerived: true,
  },
  bilirubin_total: {
    displayName: 'Total Bilirubin',
    category: 'liver',
    aliases: ['bilirubin total', 'total bilirubin', 'bilirubin', 'bilirubin, total'],
    defaultUnit: 'mg/dL',
    conversions: { 'umol/L': v => v / 17.1 },
    defaultRefMin: 0.1,
    defaultRefMax: 1.2,
    optimalMin: null,
    optimalMax: 1.0,
    panelTag: 'Core Panel',
  },
  bilirubin_direct: {
    displayName: 'Direct Bilirubin',
    category: 'liver',
    aliases: ['bilirubin direct', 'direct bilirubin', 'bilirubin, direct', 'conjugated bilirubin'],
    defaultUnit: 'mg/dL',
    conversions: { 'umol/L': v => v / 17.1 },
    defaultRefMin: 0,
    defaultRefMax: 0.3,
    optimalMin: null,
    optimalMax: 0.3,
    panelTag: 'Core Panel',
  },
  bilirubin_indirect: {
    displayName: 'Indirect Bilirubin',
    category: 'liver',
    aliases: ['bilirubin indirect', 'indirect bilirubin', 'unconjugated bilirubin'],
    defaultUnit: 'mg/dL',
    conversions: {},
    defaultRefMin: 0.1,
    defaultRefMax: 0.9,
    optimalMin: null,
    optimalMax: 0.8,
    panelTag: 'Derived',
    isDerived: true,
  },
  bar: {
    displayName: 'Bilirubin-to-Albumin Ratio (BAR)',
    category: 'liver',
    aliases: ['bar', 'bilirubin to albumin ratio', 'bilirubin/albumin ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.35,
    optimalMin: null,
    optimalMax: 0.2,
    panelTag: 'Derived',
    isDerived: true,
  },
  ggt_hdl_ratio: {
    displayName: 'GGT / HDL-C Ratio',
    category: 'liver',
    aliases: ['ggt/hdl ratio', 'ggt to hdl ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 2.5,
    optimalMin: null,
    optimalMax: 1.5,
    panelTag: 'Derived',
    isDerived: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // KIDNEY HEALTH — 10 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  creatinine: {
    displayName: 'Creatinine',
    category: 'kidney',
    aliases: ['creatinine', 'serum creatinine', 'creatinine, serum', 'creat'],
    defaultUnit: 'mg/dL',
    conversions: { 'umol/L': v => v / 88.4 },
    defaultRefMin: 0.6,
    defaultRefMax: 1.3,
    optimalMin: 0.7,
    optimalMax: 1.1,
    panelTag: 'Core Panel',
  },
  bun: {
    displayName: 'BUN',
    category: 'kidney',
    aliases: ['bun', 'blood urea nitrogen', 'urea nitrogen', 'urea'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 2.801 },
    defaultRefMin: 7,
    defaultRefMax: 20,
    optimalMin: 8,
    optimalMax: 16,
    panelTag: 'Core Panel',
  },
  bun_creatinine_ratio: {
    displayName: 'BUN / Creatinine Ratio',
    category: 'kidney',
    aliases: ['bun/creatinine ratio', 'bun creatinine ratio', 'bun/creat ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: 8,
    defaultRefMax: 20,
    optimalMin: 10,
    optimalMax: 15,
    panelTag: 'Derived',
    isDerived: true,
  },
  egfr: {
    displayName: 'eGFR',
    category: 'kidney',
    aliases: ['egfr', 'estimated gfr', 'glomerular filtration rate', 'gfr', 'estimated glomerular filtration rate'],
    defaultUnit: 'mL/min/1.73m2',
    conversions: {},
    defaultRefMin: 60,
    defaultRefMax: 999,
    optimalMin: 90,
    optimalMax: null,
    panelTag: 'Derived',
  },
  sodium: {
    displayName: 'Sodium',
    category: 'kidney',
    aliases: ['sodium', 'na', 'sodium, serum', 'na+'],
    defaultUnit: 'mEq/L',
    conversions: { 'mmol/L': v => v },
    defaultRefMin: 135,
    defaultRefMax: 145,
    optimalMin: 136,
    optimalMax: 142,
    panelTag: 'Core Panel',
  },
  potassium: {
    displayName: 'Potassium',
    category: 'kidney',
    aliases: ['potassium', 'k', 'potassium, serum', 'k+'],
    defaultUnit: 'mEq/L',
    conversions: { 'mmol/L': v => v },
    defaultRefMin: 3.5,
    defaultRefMax: 5.0,
    optimalMin: 4.0,
    optimalMax: 4.5,
    panelTag: 'Core Panel',
  },
  chloride: {
    displayName: 'Chloride',
    category: 'kidney',
    aliases: ['chloride', 'cl', 'chloride, serum', 'cl-'],
    defaultUnit: 'mEq/L',
    conversions: {},
    defaultRefMin: 96,
    defaultRefMax: 106,
    optimalMin: 100,
    optimalMax: 106,
    panelTag: 'Core Panel',
  },
  co2: {
    displayName: 'CO2 / Bicarbonate',
    category: 'kidney',
    aliases: ['co2', 'carbon dioxide', 'bicarbonate', 'hco3', 'co2, total', 'total co2'],
    defaultUnit: 'mEq/L',
    conversions: {},
    defaultRefMin: 20,
    defaultRefMax: 29,
    optimalMin: 22,
    optimalMax: 26,
    panelTag: 'Core Panel',
  },
  calcium: {
    displayName: 'Calcium',
    category: 'kidney',
    aliases: ['calcium', 'ca', 'calcium, serum', 'total calcium'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 4.008 },
    defaultRefMin: 8.5,
    defaultRefMax: 10.5,
    optimalMin: 9.0,
    optimalMax: 10.2,
    panelTag: 'Core Panel',
  },
  calcium_corrected: {
    displayName: 'Corrected Calcium',
    category: 'kidney',
    aliases: ['corrected calcium', 'calcium corrected', 'albumin-adjusted calcium', 'adjusted calcium'],
    defaultUnit: 'mg/dL',
    conversions: {},
    defaultRefMin: 8.5,
    defaultRefMax: 10.5,
    optimalMin: 9.0,
    optimalMax: 10.2,
    panelTag: 'Derived',
    isDerived: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SEX HORMONES — 22 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  testosterone_total: {
    displayName: 'Total Testosterone',
    category: 'sex_hormones',
    aliases: ['testosterone', 'total testosterone', 'testosterone total', 'testosterone, total'],
    defaultUnit: 'ng/dL',
    conversions: { 'nmol/L': v => v * 28.842 },
    defaultRefMin: 300,
    defaultRefMax: 1000,
    optimalMin: 600,
    optimalMax: 900,
    panelTag: 'Core Panel',
  },
  testosterone_free: {
    displayName: 'Free Testosterone',
    category: 'sex_hormones',
    aliases: ['free testosterone', 'testosterone free', 'testosterone, free'],
    defaultUnit: 'pg/mL',
    conversions: {},
    defaultRefMin: 46,
    defaultRefMax: 224,
    optimalMin: 130,
    optimalMax: 250,
    panelTag: 'Core Panel',
  },
  testosterone_bioavailable: {
    displayName: 'Bioavailable Testosterone',
    category: 'sex_hormones',
    aliases: ['bioavailable testosterone', 'testosterone bioavailable', 'testosterone, bioavailable'],
    defaultUnit: 'ng/dL',
    conversions: {},
    defaultRefMin: 72,
    defaultRefMax: 235,
    optimalMin: 150,
    optimalMax: 250,
    panelTag: 'Core Panel',
  },
  shbg: {
    displayName: 'SHBG',
    category: 'sex_hormones',
    aliases: ['shbg', 'sex hormone binding globulin', 'sex hormone-binding globulin'],
    defaultUnit: 'nmol/L',
    conversions: {},
    defaultRefMin: 10,
    defaultRefMax: 57,
    optimalMin: 20,
    optimalMax: 40,
    panelTag: 'Core Panel',
  },
  estradiol: {
    displayName: 'Estradiol (E2)',
    category: 'sex_hormones',
    aliases: ['estradiol', 'e2', 'estradiol, serum', 'oestradiol'],
    defaultUnit: 'pg/mL',
    conversions: {},
    defaultRefMin: 10,
    defaultRefMax: 40,
    optimalMin: 20,
    optimalMax: 30,
    panelTag: 'Core Panel',
  },
  dhea_s: {
    displayName: 'DHEA-S',
    category: 'sex_hormones',
    aliases: ['dhea-s', 'dhea sulfate', 'dehydroepiandrosterone sulfate', 'dheas'],
    defaultUnit: 'ug/dL',
    conversions: {},
    defaultRefMin: 80,
    defaultRefMax: 560,
    optimalMin: 200,
    optimalMax: 400,
    panelTag: 'Core Panel',
  },
  te2_ratio: {
    displayName: 'T:E2 Ratio',
    category: 'sex_hormones',
    aliases: ['t:e2 ratio', 'testosterone estradiol ratio', 'testosterone to estradiol ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: 8,
    defaultRefMax: null,
    optimalMin: 10,
    optimalMax: null,
    panelTag: 'Derived',
    isDerived: true,
  },
  fai: {
    displayName: 'Free Androgen Index (FAI)',
    category: 'sex_hormones',
    aliases: ['free androgen index', 'fai'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: null,
    // Sex-dependent: M optimal ≥50, F optimal 1–5. Using male defaults here;
    // sex-specific interpretation should happen in the scoring engine.
    optimalMin: 50,
    optimalMax: null,
    panelTag: 'Derived',
    isDerived: true,
  },
  fsh: {
    displayName: 'FSH',
    category: 'sex_hormones',
    aliases: ['fsh', 'follicle stimulating hormone', 'follicle-stimulating hormone'],
    defaultUnit: 'mIU/mL',
    conversions: {},
    defaultRefMin: 2,
    defaultRefMax: 13,
    optimalMin: 3,
    optimalMax: 10,
    panelTag: 'Advanced',
  },
  lh: {
    displayName: 'LH',
    category: 'sex_hormones',
    aliases: ['lh', 'luteinizing hormone'],
    defaultUnit: 'mIU/mL',
    conversions: {},
    defaultRefMin: 1,
    defaultRefMax: 18,
    optimalMin: 2,
    optimalMax: 9,
    panelTag: 'Advanced',
  },
  progesterone: {
    displayName: 'Progesterone',
    category: 'sex_hormones',
    aliases: ['progesterone', 'progesterone, serum'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: 3,
    defaultRefMax: null,
    optimalMin: 5,
    optimalMax: 20,
    panelTag: 'Advanced',
  },
  prolactin: {
    displayName: 'Prolactin',
    category: 'sex_hormones',
    aliases: ['prolactin', 'prl'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 25,
    optimalMin: 2,
    optimalMax: 15,
    panelTag: 'Advanced',
  },
  amh: {
    displayName: 'AMH',
    category: 'sex_hormones',
    aliases: ['amh', 'anti-mullerian hormone', 'anti-müllerian hormone', 'antimullerian hormone'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: 1.0,
    defaultRefMax: 3.5,
    optimalMin: 2.5,
    optimalMax: 6.8,
    panelTag: 'Advanced',
  },
  hydroxyprogesterone_17: {
    displayName: '17-Hydroxyprogesterone',
    category: 'sex_hormones',
    aliases: ['17-hydroxyprogesterone', '17 ohp', '17-ohp', '17 hydroxyprogesterone'],
    defaultUnit: 'ng/dL',
    conversions: {},
    defaultRefMin: 27,
    defaultRefMax: 199,
    optimalMin: null,
    optimalMax: 200,
    panelTag: 'Advanced',
  },
  psa_total: {
    displayName: 'PSA Total',
    category: 'sex_hormones',
    aliases: ['psa', 'psa total', 'prostate specific antigen', 'prostate-specific antigen'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 4.0,
    optimalMin: null,
    optimalMax: 2.5,
    panelTag: 'Advanced',
  },
  psa_free: {
    displayName: 'PSA Free',
    category: 'sex_hormones',
    aliases: ['psa free', 'free psa'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: null,
    optimalMin: null,
    optimalMax: null,
    panelTag: 'Advanced',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METABOLIC HEALTH — 14 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  glucose_fasting: {
    displayName: 'Fasting Glucose',
    category: 'metabolic',
    aliases: ['glucose, fasting', 'fasting glucose', 'fasting blood glucose', 'fbg', 'glucose fasting', 'blood glucose fasting', 'plasma glucose fasting'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 18.018 },
    defaultRefMin: null,
    defaultRefMax: 100,
    optimalMin: 72,
    optimalMax: 85,
    panelTag: 'Core Panel',
  },
  glucose_random: {
    displayName: 'Random Glucose',
    category: 'metabolic',
    aliases: ['glucose', 'blood glucose', 'plasma glucose', 'glucose random', 'glucose, serum'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 18.018 },
    defaultRefMin: 70,
    defaultRefMax: 140,
    optimalMin: 72,
    optimalMax: 100,
    panelTag: 'Core Panel',
  },
  hba1c: {
    displayName: 'HbA1c',
    category: 'metabolic',
    aliases: ['hemoglobin a1c', 'glycated hemoglobin', 'a1c', 'hba1c', 'glycosylated hemoglobin', 'hb a1c'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 5.7,
    optimalMin: null,
    optimalMax: 5.4,
    panelTag: 'Core Panel',
  },
  eag: {
    displayName: 'Estimated Average Glucose',
    category: 'metabolic',
    aliases: ['estimated average glucose', 'eag', 'average glucose'],
    defaultUnit: 'mg/dL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 117,
    optimalMin: null,
    optimalMax: 108,
    panelTag: 'Derived',
    isDerived: true,
  },
  insulin_fasting: {
    displayName: 'Fasting Insulin',
    category: 'metabolic',
    aliases: ['insulin', 'fasting insulin', 'insulin fasting', 'serum insulin'],
    defaultUnit: 'uIU/mL',
    conversions: { 'pmol/L': v => v / 6.945 },
    defaultRefMin: 2,
    defaultRefMax: 10,
    optimalMin: 3,
    optimalMax: 8,
    panelTag: 'Advanced',
  },
  uric_acid: {
    displayName: 'Uric Acid',
    category: 'metabolic',
    aliases: ['uric acid', 'uric acid, serum', 'urate'],
    defaultUnit: 'mg/dL',
    conversions: { 'umol/L': v => v / 59.48 },
    defaultRefMin: 3.5,
    defaultRefMax: 7.2,
    optimalMin: 3.5,
    optimalMax: 5.5,
    panelTag: 'Core Panel',
  },
  leptin: {
    displayName: 'Leptin',
    category: 'metabolic',
    aliases: ['leptin', 'serum leptin'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 12.5,
    optimalMin: 1,
    optimalMax: 5,
    panelTag: 'Advanced',
  },
  adiponectin: {
    displayName: 'Adiponectin',
    category: 'metabolic',
    aliases: ['adiponectin', 'serum adiponectin'],
    defaultUnit: 'ug/mL',
    conversions: {},
    defaultRefMin: 4,
    defaultRefMax: 26,
    optimalMin: 10,
    optimalMax: null,
    panelTag: 'Advanced',
  },
  fructosamine: {
    displayName: 'Fructosamine',
    category: 'metabolic',
    aliases: ['fructosamine', 'glycated albumin proxy'],
    defaultUnit: 'umol/L',
    conversions: {},
    defaultRefMin: 200,
    defaultRefMax: 285,
    optimalMin: null,
    optimalMax: 285,
    panelTag: 'Advanced',
  },
  tyg_index: {
    displayName: 'TyG Index',
    category: 'metabolic',
    aliases: ['tyg index', 'triglyceride glucose index', 'tyg'],
    defaultUnit: 'score',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 9.0,
    optimalMin: null,
    optimalMax: 8.5,
    panelTag: 'Derived',
    isDerived: true,
  },
  homa_ir: {
    displayName: 'HOMA-IR',
    category: 'metabolic',
    aliases: ['homa-ir', 'homa ir', 'homeostatic model assessment', 'insulin resistance index'],
    defaultUnit: 'score',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 2.5,
    optimalMin: null,
    optimalMax: 1.0,
    panelTag: 'Derived',
    isDerived: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NUTRIENTS — 20 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  hemoglobin: {
    displayName: 'Hemoglobin',
    category: 'nutrients',
    aliases: ['hemoglobin', 'hgb', 'hb', 'haemoglobin'],
    defaultUnit: 'g/dL',
    conversions: { 'g/L': v => v / 10 },
    defaultRefMin: 12.0,
    defaultRefMax: 17.5,
    optimalMin: 13.0,
    optimalMax: 17.0,
    panelTag: 'Core Panel',
  },
  hematocrit: {
    displayName: 'Hematocrit',
    category: 'nutrients',
    aliases: ['hematocrit', 'hct', 'haematocrit', 'packed cell volume', 'pcv'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 36,
    defaultRefMax: 53,
    optimalMin: 37,
    optimalMax: 48,
    panelTag: 'Core Panel',
  },
  rbc: {
    displayName: 'RBC',
    category: 'nutrients',
    aliases: ['rbc', 'red blood cells', 'red blood cell count', 'erythrocytes', 'rbc count'],
    defaultUnit: 'M/uL',
    conversions: {},
    defaultRefMin: 4.0,
    defaultRefMax: 5.5,
    optimalMin: 4.0,
    optimalMax: 5.3,
    panelTag: 'Core Panel',
  },
  mcv: {
    displayName: 'MCV',
    category: 'nutrients',
    aliases: ['mcv', 'mean corpuscular volume'],
    defaultUnit: 'fL',
    conversions: {},
    defaultRefMin: 80,
    defaultRefMax: 100,
    optimalMin: 82,
    optimalMax: 90,
    panelTag: 'Core Panel',
  },
  mch: {
    displayName: 'MCH',
    category: 'nutrients',
    aliases: ['mch', 'mean corpuscular hemoglobin'],
    defaultUnit: 'pg',
    conversions: {},
    defaultRefMin: 27,
    defaultRefMax: 33,
    optimalMin: 27,
    optimalMax: 31,
    panelTag: 'Core Panel',
  },
  mchc: {
    displayName: 'MCHC',
    category: 'nutrients',
    aliases: ['mchc', 'mean corpuscular hemoglobin concentration'],
    defaultUnit: 'g/dL',
    conversions: {},
    defaultRefMin: 32,
    defaultRefMax: 36,
    optimalMin: 33,
    optimalMax: 36,
    panelTag: 'Core Panel',
  },
  platelets: {
    displayName: 'Platelets',
    category: 'nutrients',
    aliases: ['platelets', 'platelet count', 'plt', 'thrombocytes'],
    defaultUnit: 'K/uL',
    conversions: {},
    defaultRefMin: 150,
    defaultRefMax: 400,
    optimalMin: 200,
    optimalMax: 350,
    panelTag: 'Core Panel',
  },
  mpv: {
    displayName: 'Mean Platelet Volume',
    category: 'nutrients',
    aliases: ['mpv', 'mean platelet volume'],
    defaultUnit: 'fL',
    conversions: {},
    defaultRefMin: 7.5,
    defaultRefMax: 12.5,
    optimalMin: 8,
    optimalMax: 11,
    panelTag: 'Core Panel',
  },
  rdw: {
    displayName: 'RDW',
    category: 'nutrients',
    aliases: ['rdw', 'red cell distribution width', 'rdw-cv'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 11.5,
    defaultRefMax: 14.5,
    optimalMin: null,
    optimalMax: 13.5,
    panelTag: 'Core Panel',
  },
  rdw_mcv_ratio: {
    displayName: 'RDW / MCV Ratio',
    category: 'nutrients',
    aliases: ['rdw/mcv ratio', 'rdw to mcv ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.18,
    optimalMin: null,
    optimalMax: 0.15,
    panelTag: 'Derived',
    isDerived: true,
  },
  vitamin_d: {
    displayName: 'Vitamin D (25-OH)',
    category: 'nutrients',
    aliases: ['vitamin d', '25-oh vitamin d', '25-hydroxyvitamin d', 'vitamin d 25-hydroxy', 'vitamin d total', '25(oh)d', 'calcifediol'],
    defaultUnit: 'ng/mL',
    conversions: { 'nmol/L': v => v / 2.496 },
    defaultRefMin: 30,
    defaultRefMax: 100,
    optimalMin: 40,
    optimalMax: 60,
    panelTag: 'Core Panel',
  },
  vitamin_b12: {
    displayName: 'Vitamin B12',
    category: 'nutrients',
    aliases: ['vitamin b12', 'b12', 'cobalamin', 'cyanocobalamin'],
    defaultUnit: 'pg/mL',
    conversions: { 'pmol/L': v => v / 0.7378 },
    defaultRefMin: 200,
    defaultRefMax: 900,
    optimalMin: 400,
    optimalMax: 900,
    panelTag: 'Core Panel',
  },
  vitamin_c: {
    displayName: 'Vitamin C',
    category: 'nutrients',
    aliases: ['vitamin c', 'ascorbic acid', 'ascorbate'],
    defaultUnit: 'umol/L',
    conversions: {},
    defaultRefMin: 23,
    defaultRefMax: 114,
    optimalMin: 50,
    optimalMax: 80,
    panelTag: 'Advanced',
  },
  vitamin_e: {
    displayName: 'Vitamin E',
    category: 'nutrients',
    aliases: ['vitamin e', 'alpha-tocopherol', 'alpha tocopherol'],
    defaultUnit: 'mg/L',
    conversions: {},
    defaultRefMin: 5,
    defaultRefMax: 18,
    optimalMin: 12,
    optimalMax: 20,
    panelTag: 'Advanced',
  },
  vitamin_k: {
    displayName: 'Vitamin K',
    category: 'nutrients',
    aliases: ['vitamin k', 'phylloquinone', 'vitamin k1'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: 0.2,
    defaultRefMax: 3.2,
    optimalMin: 0.4,
    optimalMax: 1.5,
    panelTag: 'Advanced',
  },
  magnesium: {
    displayName: 'Magnesium',
    category: 'nutrients',
    aliases: ['magnesium', 'mg', 'magnesium, serum'],
    defaultUnit: 'mg/dL',
    conversions: { 'mmol/L': v => v * 2.431 },
    defaultRefMin: 1.7,
    defaultRefMax: 2.5,
    optimalMin: 2.0,
    optimalMax: 2.5,
    panelTag: 'Advanced',
  },
  selenium: {
    displayName: 'Selenium',
    category: 'nutrients',
    aliases: ['selenium', 'serum selenium', 'se'],
    defaultUnit: 'ug/L',
    conversions: {},
    defaultRefMin: 70,
    defaultRefMax: 150,
    optimalMin: 110,
    optimalMax: 160,
    panelTag: 'Advanced',
  },
  folate: {
    displayName: 'Folate',
    category: 'nutrients',
    aliases: ['folate', 'folic acid', 'vitamin b9', 'folate serum'],
    defaultUnit: 'ng/mL',
    conversions: { 'nmol/L': v => v / 2.266 },
    defaultRefMin: 5.4,
    defaultRefMax: null,
    optimalMin: 10,
    optimalMax: 25,
    panelTag: 'Core Panel',
  },
  iron: {
    displayName: 'Serum Iron',
    category: 'nutrients',
    aliases: ['iron', 'serum iron', 'iron, serum', 'fe'],
    defaultUnit: 'ug/dL',
    conversions: { 'umol/L': v => v / 0.1791 },
    defaultRefMin: 60,
    defaultRefMax: 170,
    optimalMin: 80,
    optimalMax: 130,
    panelTag: 'Core Panel',
  },
  phosphorus: {
    displayName: 'Phosphorus',
    category: 'metabolic',
    aliases: ['phosphorus', 'phosphate', 'inorganic phosphorus'],
    defaultUnit: 'mg/dL',
    conversions: {},
    defaultRefMin: 2.5,
    defaultRefMax: 4.5,
    optimalMin: 3.0,
    optimalMax: 4.0,
    panelTag: 'Core Panel',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // INFLAMMATION — 9 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  hscrp: {
    displayName: 'hs-CRP',
    category: 'inflammation',
    aliases: ['hs-crp', 'hscrp', 'c-reactive protein', 'crp', 'c reactive protein', 'high sensitivity crp', 'hs crp', 'crp, high sensitivity'],
    defaultUnit: 'mg/L',
    conversions: { 'mg/dL': v => v * 10 },
    defaultRefMin: null,
    defaultRefMax: 2.0,
    optimalMin: null,
    optimalMax: 1.0,
    panelTag: 'Core Panel',
  },
  esr: {
    displayName: 'ESR',
    category: 'inflammation',
    aliases: ['esr', 'erythrocyte sedimentation rate', 'sed rate'],
    defaultUnit: 'mm/hr',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 25,
    optimalMin: null,
    optimalMax: 10,
    panelTag: 'Advanced',
  },
  ferritin: {
    displayName: 'Ferritin',
    category: 'inflammation',
    aliases: ['ferritin', 'serum ferritin', 'ferritin, serum'],
    defaultUnit: 'ng/mL',
    conversions: { 'ug/L': v => v },
    defaultRefMin: 12,
    defaultRefMax: 300,
    optimalMin: 50,
    optimalMax: 200,
    panelTag: 'Core Panel',
  },
  sii: {
    displayName: 'SII',
    category: 'inflammation',
    aliases: ['sii', 'systemic immune-inflammation index', 'systemic immune inflammation index'],
    defaultUnit: 'score',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 700,
    optimalMin: null,
    optimalMax: 500,
    panelTag: 'Derived',
    isDerived: true,
  },
  siri: {
    displayName: 'SIRI',
    category: 'inflammation',
    aliases: ['siri', 'systemic inflammation response index'],
    defaultUnit: 'score',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 1.5,
    optimalMin: null,
    optimalMax: 1.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  far: {
    displayName: 'Ferritin-to-Albumin Ratio (FAR)',
    category: 'inflammation',
    aliases: ['far', 'ferritin to albumin ratio', 'ferritin/albumin ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 12.0,
    optimalMin: null,
    optimalMax: 9.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  mhr: {
    displayName: 'Monocyte-to-HDL Ratio (MHR)',
    category: 'inflammation',
    aliases: ['mhr', 'monocyte to hdl ratio', 'monocyte-to-hdl ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 12.0,
    optimalMin: null,
    optimalMax: 8.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  car: {
    displayName: 'CRP / Albumin Ratio (CAR)',
    category: 'inflammation',
    aliases: ['car', 'crp/albumin ratio', 'crp albumin ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.06,
    optimalMin: null,
    optimalMax: 0.03,
    panelTag: 'Derived',
    isDerived: true,
  },
  plr: {
    displayName: 'Platelet-to-Lymphocyte Ratio (PLR)',
    category: 'inflammation',
    aliases: ['plr', 'platelet to lymphocyte ratio', 'platelet-to-lymphocyte ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: 50,
    defaultRefMax: 150,
    optimalMin: null,
    optimalMax: 100,
    panelTag: 'Derived',
    isDerived: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // THYROID HEALTH — 9 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  tsh: {
    displayName: 'TSH',
    category: 'thyroid',
    aliases: ['tsh', 'thyroid stimulating hormone', 'thyrotropin', 'tsh, serum'],
    defaultUnit: 'uIU/mL',
    conversions: { 'mIU/L': v => v },
    defaultRefMin: 0.45,
    defaultRefMax: 4.5,
    optimalMin: 1.0,
    optimalMax: 2.5,
    panelTag: 'Core Panel',
  },
  t4_free: {
    displayName: 'Free T4',
    category: 'thyroid',
    aliases: ['free t4', 't4 free', 'ft4', 'thyroxine free', 'free thyroxine'],
    defaultUnit: 'ng/dL',
    conversions: { 'pmol/L': v => v / 12.87 },
    defaultRefMin: 0.8,
    defaultRefMax: 1.8,
    optimalMin: 1.0,
    optimalMax: 1.4,
    panelTag: 'Core Panel',
  },
  t4_total: {
    displayName: 'Total T4',
    category: 'thyroid',
    aliases: ['total t4', 't4 total', 't4', 'thyroxine'],
    defaultUnit: 'ug/dL',
    conversions: {},
    defaultRefMin: 5.1,
    defaultRefMax: 11.9,
    optimalMin: 6.0,
    optimalMax: 9.0,
    panelTag: 'Core Panel',
  },
  t3_uptake: {
    displayName: 'T3 Uptake (THBR)',
    category: 'thyroid',
    aliases: ['t3 uptake', 'thbr', 't3 resin uptake', 'thyroid hormone binding ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: 0.85,
    defaultRefMax: 1.14,
    optimalMin: 0.97,
    optimalMax: 1.11,
    panelTag: 'Core Panel',
  },
  t7_index: {
    displayName: 'Free T4 Index (T7)',
    category: 'thyroid',
    aliases: ['free t4 index', 't7', 'ft4 index', 'fti'],
    defaultUnit: 'calculated',
    conversions: {},
    defaultRefMin: 5.5,
    defaultRefMax: 12.5,
    optimalMin: 6.0,
    optimalMax: 11.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  t3_free: {
    displayName: 'Free T3',
    category: 'thyroid',
    aliases: ['free t3', 't3 free', 'ft3', 'triiodothyronine free', 'free triiodothyronine'],
    defaultUnit: 'pg/mL',
    conversions: { 'pmol/L': v => v / 1.536 },
    defaultRefMin: 2.3,
    defaultRefMax: 4.2,
    optimalMin: 3.2,
    optimalMax: 3.8,
    panelTag: 'Advanced',
  },
  t3_total: {
    displayName: 'Total T3',
    category: 'thyroid',
    aliases: ['total t3', 't3 total', 't3', 'triiodothyronine'],
    defaultUnit: 'ng/dL',
    conversions: {},
    defaultRefMin: 80,
    defaultRefMax: 200,
    optimalMin: 100,
    optimalMax: 180,
    panelTag: 'Core Panel',
  },
  tpo_ab: {
    displayName: 'TPO Antibodies',
    category: 'thyroid',
    aliases: ['tpo-ab', 'tpo antibodies', 'thyroid peroxidase antibodies', 'tpo ab', 'anti-tpo', 'thyroid peroxidase ab'],
    defaultUnit: 'IU/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 34,
    optimalMin: null,
    optimalMax: 9,
    panelTag: 'Autoimmunity',
  },
  tgab: {
    displayName: 'Thyroglobulin Antibodies',
    category: 'thyroid',
    aliases: ['tgab', 'thyroglobulin antibodies', 'anti-thyroglobulin', 'tg ab', 'anti-tg'],
    defaultUnit: 'IU/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 4,
    optimalMin: null,
    optimalMax: 1,
    panelTag: 'Autoimmunity',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ENERGY — 6 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  tibc: {
    displayName: 'TIBC',
    category: 'energy',
    aliases: ['tibc', 'total iron binding capacity', 'iron binding capacity'],
    defaultUnit: 'ug/dL',
    conversions: {},
    defaultRefMin: 240,
    defaultRefMax: 450,
    optimalMin: 240,
    optimalMax: 310,
    panelTag: 'Core Panel',
  },
  transferrin_saturation: {
    displayName: 'Transferrin Saturation',
    category: 'energy',
    aliases: ['transferrin saturation', 'iron saturation', 'tsat', 'iron sat', 'transferrin sat'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 20,
    defaultRefMax: 50,
    optimalMin: 25,
    optimalMax: 40,
    panelTag: 'Derived',
    isDerived: true,
  },
  cortisol: {
    displayName: 'Cortisol (Morning)',
    category: 'energy',
    aliases: ['cortisol', 'serum cortisol', 'cortisol, serum', 'cortisol am', 'morning cortisol'],
    defaultUnit: 'ug/dL',
    conversions: { 'nmol/L': v => v / 27.59 },
    defaultRefMin: 6,
    defaultRefMax: 23,
    optimalMin: 12,
    optimalMax: 18,
    panelTag: 'Core Panel',
  },
  bmi: {
    displayName: 'BMI',
    category: 'energy',
    aliases: ['bmi', 'body mass index'],
    defaultUnit: 'kg/m²',
    conversions: {},
    defaultRefMin: 18.5,
    defaultRefMax: 24.9,
    optimalMin: 20,
    optimalMax: 22,
    panelTag: 'Core Panel',
    isDerived: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // IMMUNE SYSTEM — 21 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  wbc: {
    displayName: 'WBC',
    category: 'immune',
    aliases: ['wbc', 'white blood cells', 'white blood cell count', 'leukocytes', 'wbc count'],
    defaultUnit: 'K/uL',
    conversions: {},
    defaultRefMin: 4.5,
    defaultRefMax: 11.0,
    optimalMin: 5.0,
    optimalMax: 8.0,
    panelTag: 'Core Panel',
  },
  neutrophils_pct: {
    displayName: 'Neutrophils (%)',
    category: 'immune',
    aliases: ['neutrophils %', 'neutrophils', 'neutrophil %', 'neut %', 'granulocytes %'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 45,
    defaultRefMax: 75,
    optimalMin: 50,
    optimalMax: 65,
    panelTag: 'Core Panel',
  },
  neutrophils_abs: {
    displayName: 'Neutrophils (Absolute)',
    category: 'immune',
    aliases: ['neutrophils absolute', 'absolute neutrophils', 'anc', 'neutrophils abs', 'absolute neutrophil count'],
    defaultUnit: 'K/uL',
    conversions: {},
    defaultRefMin: 1.8,
    defaultRefMax: 7.7,
    optimalMin: 2.5,
    optimalMax: 5.0,
    panelTag: 'Core Panel',
  },
  lymphocytes_pct: {
    displayName: 'Lymphocytes (%)',
    category: 'immune',
    aliases: ['lymphocytes %', 'lymphocytes', 'lymphocyte %', 'lymph %'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 20,
    defaultRefMax: 40,
    optimalMin: 25,
    optimalMax: 40,
    panelTag: 'Core Panel',
  },
  lymphocytes_abs: {
    displayName: 'Lymphocytes (Absolute)',
    category: 'immune',
    aliases: ['lymphocytes absolute', 'absolute lymphocytes', 'lymphocytes abs', 'absolute lymphocyte count'],
    defaultUnit: 'K/uL',
    conversions: {},
    defaultRefMin: 1.0,
    defaultRefMax: 4.8,
    optimalMin: 1.5,
    optimalMax: 3.0,
    panelTag: 'Core Panel',
  },
  monocytes_pct: {
    displayName: 'Monocytes (%)',
    category: 'immune',
    aliases: ['monocytes %', 'monocytes', 'monocyte %', 'mono %'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 2,
    defaultRefMax: 8,
    optimalMin: 5,
    optimalMax: 10,
    panelTag: 'Core Panel',
  },
  monocytes_abs: {
    displayName: 'Monocytes (Absolute)',
    category: 'immune',
    aliases: ['monocytes absolute', 'absolute monocytes', 'monocytes abs'],
    defaultUnit: 'K/uL',
    conversions: {},
    defaultRefMin: 0.2,
    defaultRefMax: 1.0,
    optimalMin: 0.3,
    optimalMax: 0.7,
    panelTag: 'Core Panel',
  },
  eosinophils_pct: {
    displayName: 'Eosinophils (%)',
    category: 'immune',
    aliases: ['eosinophils %', 'eosinophils', 'eosinophil %', 'eos %'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 1,
    defaultRefMax: 4,
    optimalMin: 1,
    optimalMax: 3,
    panelTag: 'Core Panel',
  },
  eosinophils_abs: {
    displayName: 'Eosinophils (Absolute)',
    category: 'immune',
    aliases: ['eosinophils absolute', 'absolute eosinophils', 'eosinophils abs'],
    defaultUnit: 'K/uL',
    conversions: {},
    defaultRefMin: 0.05,
    defaultRefMax: 0.5,
    optimalMin: 0.05,
    optimalMax: 0.25,
    panelTag: 'Core Panel',
  },
  basophils_pct: {
    displayName: 'Basophils (%)',
    category: 'immune',
    aliases: ['basophils %', 'basophils', 'basophil %', 'baso %'],
    defaultUnit: '%',
    conversions: {},
    defaultRefMin: 0,
    defaultRefMax: 1,
    optimalMin: 0.5,
    optimalMax: 1.0,
    panelTag: 'Core Panel',
  },
  basophils_abs: {
    displayName: 'Basophils (Absolute)',
    category: 'immune',
    aliases: ['basophils absolute', 'absolute basophils', 'basophils abs'],
    defaultUnit: 'K/uL',
    conversions: {},
    defaultRefMin: 0,
    defaultRefMax: 0.1,
    optimalMin: 0.01,
    optimalMax: 0.05,
    panelTag: 'Core Panel',
  },
  nlr: {
    displayName: 'Neutrophil-to-Lymphocyte Ratio (NLR)',
    category: 'immune',
    aliases: ['nlr', 'neutrophil to lymphocyte ratio', 'neutrophil-to-lymphocyte ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: 1.0,
    defaultRefMax: 3.0,
    optimalMin: null,
    optimalMax: 2.0,
    panelTag: 'Derived',
    isDerived: true,
  },
  lmr: {
    displayName: 'Lymphocyte-to-Monocyte Ratio (LMR)',
    category: 'immune',
    aliases: ['lmr', 'lymphocyte to monocyte ratio', 'lymphocyte-to-monocyte ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: 3.0,
    defaultRefMax: null,
    optimalMin: 5.0,
    optimalMax: null,
    panelTag: 'Derived',
    isDerived: true,
  },
  mlr: {
    displayName: 'Monocyte-to-Lymphocyte Ratio (MLR)',
    category: 'immune',
    aliases: ['mlr', 'monocyte to lymphocyte ratio', 'monocyte-to-lymphocyte ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.3,
    optimalMin: null,
    optimalMax: 0.2,
    panelTag: 'Derived',
    isDerived: true,
  },
  nlpr: {
    displayName: 'NLPR',
    category: 'immune',
    aliases: ['nlpr', 'neutrophil lymphocyte platelet ratio'],
    defaultUnit: 'ratio',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 0.03,
    optimalMin: null,
    optimalMax: 0.02,
    panelTag: 'Derived',
    isDerived: true,
  },
  rheumatoid_factor: {
    displayName: 'Rheumatoid Factor (RF)',
    category: 'immune',
    aliases: ['rheumatoid factor', 'rf', 'ra factor'],
    defaultUnit: 'IU/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 14,
    optimalMin: null,
    optimalMax: 0,
    panelTag: 'Autoimmunity',
  },
  anti_ccp: {
    displayName: 'Anti-CCP Antibody',
    category: 'immune',
    aliases: ['anti-ccp', 'ccp ab', 'anti-ccp antibody', 'cyclic citrullinated peptide'],
    defaultUnit: 'U/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 20,
    optimalMin: null,
    optimalMax: 0,
    panelTag: 'Autoimmunity',
  },
  ana: {
    displayName: 'ANA',
    category: 'immune',
    aliases: ['ana', 'antinuclear antibody', 'antinuclear antibodies'],
    defaultUnit: 'titer',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: null,
    optimalMin: null,
    optimalMax: null,
    panelTag: 'Autoimmunity',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BODY COMPOSITION — 1 biomarker
  // ═══════════════════════════════════════════════════════════════════════════
  igf1: {
    displayName: 'IGF-1',
    category: 'body_composition',
    aliases: ['igf-1', 'igf1', 'insulin-like growth factor 1', 'insulin like growth factor', 'igf 1'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: null,
    optimalMin: 175,
    optimalMax: 250,
    panelTag: 'Advanced',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DNA HEALTH — 6 biomarkers
  // ═══════════════════════════════════════════════════════════════════════════
  homocysteine: {
    displayName: 'Homocysteine',
    category: 'dna_health',
    aliases: ['homocysteine', 'hcy', 'homocysteine, serum'],
    defaultUnit: 'umol/L',
    conversions: {},
    defaultRefMin: null,
    defaultRefMax: 10,
    optimalMin: null,
    optimalMax: 8.0,
    panelTag: 'Advanced',
  },
  folate_rbc: {
    displayName: 'Folate (RBC)',
    category: 'dna_health',
    aliases: ['folate rbc', 'rbc folate', 'red blood cell folate'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: 280,
    defaultRefMax: null,
    optimalMin: 280,
    optimalMax: 500,
    panelTag: 'Methylation',
  },
  vitamin_b6: {
    displayName: 'Vitamin B6 (PLP)',
    category: 'dna_health',
    aliases: ['vitamin b6', 'pyridoxal-5-phosphate', 'plp', 'pyridoxal 5 phosphate', 'b6'],
    defaultUnit: 'ng/mL',
    conversions: {},
    defaultRefMin: 20,
    defaultRefMax: 125,
    optimalMin: 40,
    optimalMax: 80,
    panelTag: 'Methylation',
  },
  mma: {
    displayName: 'Methylmalonic Acid (MMA)',
    category: 'dna_health',
    aliases: ['mma', 'methylmalonic acid'],
    defaultUnit: 'nmol/L',
    conversions: {},
    defaultRefMin: 87,
    defaultRefMax: 318,
    optimalMin: null,
    optimalMax: 243,
    panelTag: 'Methylation',
  },
}

// Build lookup index: lowercase alias → canonical name
const ALIAS_INDEX = new Map()
for (const [canonical, entry] of Object.entries(CANONICAL_MAP)) {
  // Index the canonical name itself
  ALIAS_INDEX.set(canonical.toLowerCase(), canonical)
  ALIAS_INDEX.set(entry.displayName.toLowerCase(), canonical)
  for (const alias of entry.aliases) {
    ALIAS_INDEX.set(alias.toLowerCase(), canonical)
  }
}

function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')
}

function tokenOverlap(a, b) {
  const tokensA = new Set(a.toLowerCase().split(/\W+/).filter(Boolean))
  const tokensB = new Set(b.toLowerCase().split(/\W+/).filter(Boolean))
  const intersection = [...tokensA].filter(t => tokensB.has(t))
  const union = new Set([...tokensA, ...tokensB])
  return union.size > 0 ? intersection.length / union.size : 0
}

function matchCanonical(testName) {
  const lower = testName.toLowerCase().trim()

  // Exact match
  if (ALIAS_INDEX.has(lower)) return ALIAS_INDEX.get(lower)

  // Token overlap matching (>0.6 threshold)
  let bestMatch = null
  let bestScore = 0
  for (const [canonical, entry] of Object.entries(CANONICAL_MAP)) {
    for (const alias of [entry.displayName, ...entry.aliases]) {
      const score = tokenOverlap(lower, alias)
      if (score > bestScore && score > 0.6) {
        bestScore = score
        bestMatch = canonical
      }
    }
  }
  if (bestMatch) return bestMatch

  // Fallback — slugified name
  return slugify(testName)
}

function parseNumericValue(value) {
  if (typeof value === 'number') return value
  if (typeof value !== 'string') return null
  // Handle ranges like ">100" or "<5" — take the number
  const cleaned = value.replace(/[<>≤≥]/g, '').trim()
  const num = parseFloat(cleaned)
  return isNaN(num) ? null : num
}

function determineFlag(value, refMin, refMax) {
  if (value == null || (refMin == null && refMax == null)) return 'normal'
  if (refMin != null && value < refMin) return refMin != null && value < refMin * 0.7 ? 'critical_low' : 'low'
  if (refMax != null && refMax < 999 && value > refMax) return refMax != null && value > refMax * 1.3 ? 'critical_high' : 'high'
  return 'normal'
}

/**
 * Determine optimal flag — how the value compares to Superpower optimal ranges.
 */
function determineOptimalFlag(value, entry) {
  if (value == null || !entry) return null
  const { optimalMin, optimalMax } = entry
  if (optimalMin != null && optimalMax != null) {
    if (value >= optimalMin && value <= optimalMax) return 'optimal'
    return 'suboptimal'
  }
  if (optimalMin != null) return value >= optimalMin ? 'optimal' : 'suboptimal'
  if (optimalMax != null) return value <= optimalMax ? 'optimal' : 'suboptimal'
  return null
}

/**
 * Normalize tests from a parsed report into canonical format.
 * @param {Object} parsedData - The parsedData from a ReportData doc
 * @returns {Array} normalizedTests
 */
function normalizeTests(parsedData) {
  if (!parsedData) return []

  // Collect all tests from both tests[] and panels[].tests[]
  const rawTests = []

  if (Array.isArray(parsedData.tests)) {
    for (const t of parsedData.tests) rawTests.push(t)
  }
  if (Array.isArray(parsedData.panels)) {
    for (const panel of parsedData.panels) {
      if (Array.isArray(panel.tests)) {
        for (const t of panel.tests) rawTests.push(t)
      }
    }
  }

  const seen = new Set()
  const normalized = []

  for (const test of rawTests) {
    const name = test.testName || test.name || test.test_name || ''
    if (!name) continue

    const numericValue = parseNumericValue(test.value ?? test.result)
    if (numericValue == null) continue // Skip non-numeric

    const canonicalName = matchCanonical(name)
    if (seen.has(canonicalName)) continue // Deduplicate
    seen.add(canonicalName)

    const entry = CANONICAL_MAP[canonicalName]
    const unit = test.unit || test.units || entry?.defaultUnit || ''

    // Convert unit if needed
    let finalValue = numericValue
    if (entry && unit && entry.conversions[unit]) {
      finalValue = Math.round(entry.conversions[unit](numericValue) * 100) / 100
    }

    const refMin = parseNumericValue(test.referenceMin ?? test.refMin ?? test.normalMin) ?? entry?.defaultRefMin ?? null
    const refMax = parseNumericValue(test.referenceMax ?? test.refMax ?? test.normalMax) ?? entry?.defaultRefMax ?? null
    const flag = test.flag || determineFlag(finalValue, refMin, refMax)
    const optimalFlag = determineOptimalFlag(finalValue, entry)

    normalized.push({
      canonicalName,
      displayName: entry?.displayName || name,
      category: entry?.category || 'other',
      numericValue: finalValue,
      unit: entry?.defaultUnit || unit,
      referenceMin: refMin,
      referenceMax: refMax,
      optimalMin: entry?.optimalMin ?? null,
      optimalMax: entry?.optimalMax ?? null,
      flag,
      optimalFlag,
      panelTag: entry?.panelTag || 'Core Panel',
    })
  }

  return normalized
}


module.exports = { CANONICAL_MAP, ALIAS_INDEX, matchCanonical, parseNumericValue, determineFlag, determineOptimalFlag, normalizeTests };
