const PDFDocument = require("pdfkit");

const generateActionPlanPDF = (plan) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 40,
        size: "A4",
      });

      let buffers = [];
      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      // Header
      doc.fontSize(28).font("Helvetica-Bold").text("Your Action Plan", { align: "center" });
      doc.fontSize(12).fillColor("#666").text("Personalized Health Roadmap", { align: "center" });
      doc.moveDown(1);

      // Summary
      if (plan.summary) {
        doc
          .fontSize(16)
          .font("Helvetica-Bold")
          .fillColor("#000")
          .text("Overview");
        doc.fontSize(12).fillColor("#333").text(plan.summary, { align: "left" });
        doc.moveDown(0.8);
      }

      // Recommendations
      if (plan.recommendations && Array.isArray(plan.recommendations)) {
        doc.fontSize(16).font("Helvetica-Bold").fillColor("#000").text("Recommendations");
        doc.moveDown(0.4);

        plan.recommendations.forEach((section, idx) => {
          // Section title
          doc
            .fontSize(13)
            .font("Helvetica-Bold")
            .fillColor("#333")
            .text(`${section.title}`, { indent: 0 });

          // Items
          if (section.items && Array.isArray(section.items)) {
            section.items.forEach((item) => {
              doc
                .fontSize(11)
                .font("Helvetica")
                .fillColor("#555")
                .text(`• ${item}`, { indent: 20, width: 460 });
            });
          }

          doc.moveDown(0.5);
        });
      }

      // Labs Reviewed
      if (plan.labsReviewed) {
        doc.fontSize(14).font("Helvetica-Bold").fillColor("#000").text("Labs Reviewed");
        doc
          .fontSize(11)
          .font("Helvetica")
          .fillColor("#555")
          .text(`Report: ${plan.labsReviewed.fileName}`);
        doc.fontSize(10).fillColor("#888").text(
          `Uploaded: ${new Date(plan.labsReviewed.uploadedAt).toLocaleDateString()}`
        );
        doc.moveDown(1);
      }

      // Footer
      doc
        .fontSize(9)
        .fillColor("#999")
        .text("Generated by Cyborg • Your Personal Health AI", { align: "center" });
      doc.text(`${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, {
        align: "center",
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateActionPlanPDF };
